# Generated by Django 4.0.3 on 2022-03-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eligible', models.BooleanField(default=False)),
                ('program_name', models.TextField()),
                ('currency', models.TextField()),
                ('country_name', models.TextField()),
                ('bank_name', models.TextField()),
            ],
        ),
    ]
